---
jupyter: python3
---

# Tarea 1 {.unnumbered}

#### Ejercicio 1.- Explique ¿Por qué el aprendizaje reforzado se diferencia del aprendizaje supervisado y del no supervisado?

El aprendizaje reforzado se distingue por ser un método de aprendizaje que considera las investigaciones tipo prueba y error; y las recompensas retrasadas. Lo que hace que este método se ha más adecuado para los problemas interactivos en comparación con el aprendizaje supervisado y no supervisado. Lo anterior se debe a la dificultad que tienen los problemas interactivos al momento de generar muestras de datos que sean tanto correctos como representativos de todas las situaciones en las que el agente debe actuar. Las muestras de datos son necesarias para que los aprendizaje supervisado y no supervisado puedan ser utilizados.

#### Ejercicio 2.- De acuerdo al video de Steve Brunton, explique cuál es el significado de la siguiente expresión:

$$ V_{\pi}(s)=E {\LARGE(} \sum_{t} \gamma^{t}r_{t}|s_{0}=s{\LARGE)} $$

$V_{\pi}(s)$ nos permite medir la recompensa esperada en el futuro si empiezo en el estado $s$ y usando la política $\pi$. Esto quiere decir que para saber si nuestra política es buena o mala, se tienen que observar que tal buen valor se tiene en ese estado.

Un ejemplo puede ser en una partida de Blackjack si mis primas dos cartas junto 20 pts, y mis compañeros sus cartas expuestas están en el rango 6-9 pts. Yo probablemente tenga una mejor oportunidad de ganar. Ya que mis compañeros tienen más chance de pasarse de puntos.

```{python}
1 + 1
```
